### ISSUE TITLE
Progress on nitransforms?

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/czi-nibabel#1]
@oesteban - thanks for the nitransforms notes.

Have you done any of the milestones that you mention at the end of the nitransforms notes?

**Comment by oesteban** [comment]
> CO3.1. Submission to Journal of Open Source Software [[nitransforms#44](https://github.com/poldracklab/nitransforms/issues/44), month 1].

(CO = community outreach) Submission is ready, we would just need to hit send (probably at this point we may want to revise and add other people in the team as authors). But things are at 90%.

SD3.2. Support for ITK's HDF5-format transforms [[nitransforms#4](https://github.com/poldracklab/nitransforms/issues/4), month 1]

Done, although I recently found a bug that I'm still analyzing to report a new issue.

SD3.3. Implement transforms mappings [[nitransforms#46](https://github.com/poldracklab/nitransforms/issues/46), month 2]

Done

SD3.4. Revise unit tests [[nitransforms#37](https://github.com/poldracklab/nitransforms/issues/37), [nitransforms#40](https://github.com/poldracklab/nitransforms/issues/40), [nitransforms#52](https://github.com/poldracklab/nitransforms/issues/52), month 3].

Not started

SD3.5. Generate API documentation [[nitransforms#58](https://github.com/poldracklab/nitransforms/issues/58), month 3].

Not started (docstrings are there though)

SD3.6. Implement the inversion of nonlinear, nonparametric transforms [[nitransforms#56](https://github.com/poldracklab/nitransforms/issues/56), months 3-5]

Not started

SD3.7. Support for nonparametric transforms of surfaces [[nitransforms#57](https://github.com/poldracklab/nitransforms/issues/57), months 5-12].

Not started

SD3.8. Integration into NiBabel [month 12].

hehehe

**Comment by matthew-brett** [comment]
@oesteban - can you check the current state of `work_plan.md` - does the text agree with what you are thinking?

**Comment by oesteban** [comment]
Looked through it quickly, seems reasonable. Will send a PR later on suggesting some minimal improvements.

**Comment by matthew-brett** [comment]
Do we need to define any HDF format for transforms?  Or does the ITK HDF5 format suffice?

**Comment by oesteban** [comment]
There is a draft of an HDF5 format for transforms under the BIDS-Derivatives grant called X5. To define it, representatives from ITK, FreeSurfer, AFNI, ANTs, FSL, SPM and niftyreg were present. I'll search for the link. Some areas of the format are still blurry (those transforms chains Chris mentioned in our last call), and it is strongly influenced by ITK's h5.

Short answer - no we don't, such format is already defined.

**Comment by matthew-brett** [comment]
OK - I think we've processed these.
