### ISSUE TITLE
Brendan's time?

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/czi-nibabel#15]
@moloney - we need to put you into `work_plan.md` - on the lines of "Brendan Moloney, author of Dcmstack, will commit x hours per week to this effort". 

Are you still sure we can't pay you?  If you can get paid as a consultant, we can still add you.    Time running out fast though ...

https://docs.google.com/spreadsheets/d/1srftwgEl-3_sdVlxd1flCmayUNTXQT5x71aO04IhWJ8

**Comment by moloney** [comment]
Sorry for dropping the ball on this...  Since I can't accept any funding currently, I wouldn't be able to commit to any specific amount of hours.  Any work I do on this will be incidental as part of my job (we are ramping up some projects that need this stuff) or in my own free time.
