### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/czi-nibabel#17]
@oesteban  - I've done my first pass - can you have a look, and add your milestones?

**Comment by oesteban** [comment]
See #18

**Comment by effigies** [comment]
@oesteban It looks like you set milestone time estimates to durations, not completion times relative to grant start. Is that correct?

**Comment by effigies** [comment]
FWIW I'm comfortable with the Xarray and surface API milestones.

**Comment by oesteban** [comment]
> @oesteban It looks like you set milestone time estimates to durations, not completion times relative to grant start. Is that correct?

correct, let me revise
