### ISSUE TITLE
Contributions to other projects

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/czi-nibabel#2]
@effigies @oesteban @moloney - can you have a look at the `todo.md` file? There is a section, currently like this:

```
### List of upstream, downstream, or related software projects that the team is contributing to or receiving contributions from:

Matthew Brett contributions (number of commits):

Upstream:
    Numpy : 94
    Scipy : 281
    Statsmodels : 59
    Matplotlib : 56

Downstream:
    Nipy : 1657
    Dipy : 564

Downstream contributions back (number of commits, ):
    Dipy : 185
    FSL : 108
    PyMVPA : 87
    Nipype : 65
    dcmstack : 22
    MNE : 15
```

Can you see if y'all have contributed stuff to upstream or downstream projects, and fill the details in, in the todo file?

**Comment by effigies** [comment]
Not sure I understand what "Downstream contributions back" means. As in, the number of contributions to nibabel from members/leads of those projects?

**Comment by matthew-brett** [comment]
Yes - that's what I took it to mean ...

**Comment by matthew-brett** [comment]
All done now, thanks.
