### ISSUE TITLE
Do we have any financial or in-kind support?

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/czi-nibabel#4]
We have to answer this question:

> List current and recent financial or in-kind support for the software
> project(s), including duration, amount in USD, and source of funding. Include
> in this section any previous funding for these software projects received
> from CZI 

@effigies - do you get any support from grants for Nibabel work?  @oesteban or @moloney - do you?

**Comment by effigies** [comment]
Not directly, although working on nibabel during work hours is not considered a problem. We do incidentally address issues when they affect projects we are paid to work on...

Clarifying whether this constitutes in kind by Stanford, but might as well describe that here.

**Comment by oesteban** [comment]
Nitransforms has had some NIH funding, but very indirectly and long ago

**Comment by effigies** [comment]
Update from Russ: No contributions that require reporting, but if it's helpful to mention that we do contribute upstream to nibabel when working on other projects, it's certainly true.

**Comment by moloney** [comment]
I haven't gotten any grants to work on dcmstack or nibabel, although I have done work on both during the course of my job.

**Comment by oesteban** [comment]
for nitransforms we had an R24 with which we developed the draft of X5 (I don't think this counts as funding). Then I had support from Russ for nitransforms... but similarly, that can be considered an upstream contribution.
