### ISSUE TITLE
DEI: Hackathon leading to improved diversity

### ISSUE THREAD

**Issue by effigies** [matthew-brett/czi-nibabel#9]
CJM: Add some words to DEI statement.

**Comment by effigies** [comment]
Quick text (46 words):

Developer participation in hackathons that also seek to promote equity has directly led to two significant sprints on Nibabel led by underrepresented minority contributors. Continued outreach in the form of hackathon participation is one component of our strategy to make our project welcoming to diverse contributors.

**Comment by matthew-brett** [comment]
Thanks - I put something into the `todo.md` file diversity section.

**Comment by matthew-brett** [comment]
Closing this - I think I've put something in - reopen of you want me to rewrite?

**Comment by effigies** [comment]
LGTM.
